version: "3.9"

services:
    php-fpm:
        container_name: 'dev-platform-demo-app-php-fpm'
        restart: "unless-stopped"
        build:
            context: _docker/config/php-fpm
            dockerfile: Dockerfile
        #            args:
        #                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./:/var/www/application
        networks:
            dev_private: ~
            dev_internal:
                ipv4_address: ${ADDR_IP_DEMO_PHP_FPM}
        env_file:
            - .env

    nginx:
        container_name: "dev-platform-demo-app-php-nginx"
        restart:        "unless-stopped"
        build:
            context:    ./_docker/config/nginx
            dockerfile: Dockerfile
        links:
            - php-fpm
        volumes_from:
            - php-fpm
        networks:
            dev_private: ~
            dev_internal:
                ipv4_address: ${ADDR_IP_DEMO_NGINX}

networks:
    dev_private:
        driver: bridge
    dev_internal:
        external:
            name: dev-platform_internal-network
